"""Research method components implemented by TDWM."""

from .goal_tail import (
    GoalTailTDOutput,
    GoalTailValue,
    discounted_goal_tail_target,
    ema_update,
    future_goal_td_objective,
    goal_cost,
    goal_tail_loss,
)
from .local_successor import (
    GoalConditionedPolicy,
    LocalSuccessorHeads,
    SuccessorPredictor,
    SuccessorTDOutput,
    future_goal_successor_objective,
    successor_td_target,
)
from .rf_successor_lewm import (
    ActionPrefixMomentHead,
    ActionPrefixSuccessorHead,
    MomentSequenceOutput,
    MultiHorizonSuccessorOutput,
    SuccessorSequenceOutput,
    finite_horizon_successor_from_moments,
    finite_horizon_successor_targets,
    latent_sequence_from_successor,
    moment_sequence_objective,
    multi_horizon_successor_objective,
    successor_moments_from_sequence,
    successor_recurrence_residual,
    successor_sequence_objective,
)
from .successor_geometry import (
    goal_cost_weights,
    latent_goal_cost,
    successor_feature_basis,
    successor_goal_cost,
)

__all__ = [
    "ActionPrefixMomentHead",
    "ActionPrefixSuccessorHead",
    "GoalConditionedPolicy",
    "GoalTailTDOutput",
    "GoalTailValue",
    "LocalSuccessorHeads",
    "MomentSequenceOutput",
    "MultiHorizonSuccessorOutput",
    "SuccessorPredictor",
    "SuccessorSequenceOutput",
    "SuccessorTDOutput",
    "discounted_goal_tail_target",
    "ema_update",
    "finite_horizon_successor_from_moments",
    "finite_horizon_successor_targets",
    "future_goal_successor_objective",
    "future_goal_td_objective",
    "goal_cost",
    "goal_cost_weights",
    "goal_tail_loss",
    "latent_goal_cost",
    "latent_sequence_from_successor",
    "moment_sequence_objective",
    "multi_horizon_successor_objective",
    "successor_feature_basis",
    "successor_goal_cost",
    "successor_moments_from_sequence",
    "successor_recurrence_residual",
    "successor_sequence_objective",
    "successor_td_target",
]
